### PR TITLE
Typo, grammatical fixes on README; also provided a short example on usage and rationale.

### PR DESCRIPTION
**Pull request by burritofanatic**

### CODE REVIEW

**Comment by yar1vn** [comment]
Great updates! Thanks

**Comment by burritofanatic** [comment]
Welcome! I listened to your appearance on Garric's podcast, sounds like you've had some pretty interesting experiences, very cool.

**Comment by yar1vn** [comment]
We should definitely meet and talk about our experiences. I'm trying to find time to listen to all of the interviews this weekend. Come to our meetup on Wednesday if you can

**Comment by burritofanatic** [comment]
Marina Del Rey, nice. I'll try to make it out.

**Pull request merged**
